### ISSUE TITLE
singleton_map is too limited

### ISSUE THREAD

**Issue by asomers** [acatton/serde-yaml-ng#1]
Thanks for picking up this very useful crate!  I learned about it on the forum.  While I understand why dtolnay wanted to abandon it, the limitations he pointed to don't apply to my use case.  For me, the crate is perfect.  Nearly perfect, anyway.

The [singleton_map](https://docs.rs/serde_yaml_ng/latest/serde_yaml_ng/with/singleton_map/index.html) is useful for opting out of the new enum serialization behavior introduced in serde_yaml 0.9. But it's a little bit too limited.

* It can't be used in combination with a field that needs another `serialize_with` attribute for some other reason
* It can't be used within a struct that has a custom `Serialize` or `Deserialize` implementation.

Would it be possible to relax these restrictions? An easy way would be to simply make the `SingletonMap` structure public.  I can submit a PR if you'd accept such a thing.

**Comment by acatton** [comment]
I just saw the thread on the user forum, and chimed in in there. This is something I can try to take a stab at it.

**Comment by acatton** [comment]
This is fixed in https://crates.io/crates/serde_yaml_ng/0.10.0
