### ISSUE TITLE
Document YAML specification version

### ISSUE THREAD

**Issue by russellbanks** [acatton/serde-yaml-ng#2]
See https://github.com/dtolnay/serde-yaml/issues/400.

dtolnay mentioned that serde_yaml's current codebase "does not have line-of-site to supporting anything newer than YAML 1.1" - https://fosstodon.org/@mo8it/112158090015890687.

If the crate in its current state doesn't support the newest spec fully, it would be nice to work towards that.

**Comment by acatton** [comment]
Let's keep this issue about the documentation, which is a fair point, and continue on YAML 1.2 in #3
